import { useState, type FormEvent } from "react";
import { motion } from "framer-motion";
import { Camera, CheckCircle2, Clock3, History, Link2, Plus, ShieldCheck, Sparkles, UsersRound, Video } from "lucide-react";
import { useTranslation } from "react-i18next";
import { LoginHistoryDialog } from "@/modules/auth";
import { Avatar, Button, Dialog, DialogContent, LoadingFallback, RouteState } from "@/shared/ui/legacy";
import { useCreateChild, useParentChildren, useParentConsents, useRequestChildLink, useSelectedChild, useSetParentConsent, type ConsentKind } from "@/modules/parent";

const emptyChild = { username: "", password: "", first_name: "", last_name: "" };

function useConsentKinds(): Array<{ id: ConsentKind; label: string; description: string; icon: typeof Video }> {
  const { t } = useTranslation("parent");
  return [
    { id: "recording", label: t("children.consentKinds.recording.label"), description: t("children.consentKinds.recording.description"), icon: Video },
    { id: "camera", label: t("children.consentKinds.camera.label"), description: t("children.consentKinds.camera.description"), icon: Camera },
    { id: "analytics", label: t("children.consentKinds.analytics.label"), description: t("children.consentKinds.analytics.description"), icon: Sparkles },
  ];
}

export function ParentChildrenPage() {
  const { t } = useTranslation("parent");
  const consentKinds = useConsentKinds();
  const childrenQuery = useParentChildren(); const consents = useParentConsents(); const requestLink = useRequestChildLink(); const createChild = useCreateChild(); const setConsent = useSetParentConsent(); const { selectedChild, selectedChildId, selectChild } = useSelectedChild();
  const [linkOpen, setLinkOpen] = useState(false); const [childOpen, setChildOpen] = useState(false); const [loginsOpen, setLoginsOpen] = useState(false); const [inviteCode, setInviteCode] = useState(""); const [child, setChild] = useState(emptyChild); const [formError, setFormError] = useState("");
  async function submitLink(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFormError(""); try { await requestLink.mutateAsync(inviteCode.trim()); setInviteCode(""); setLinkOpen(false); } catch (error) { setFormError(error instanceof Error ? error.message : t("children.genericError")); } }
  async function submitChild(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFormError(""); try { await createChild.mutateAsync(child); setChild(emptyChild); setChildOpen(false); } catch (error) { setFormError(error instanceof Error ? error.message : t("children.genericError")); } }
  function toggleConsent(kind: ConsentKind) { const current = (consents.data ?? []).find((item) => item.studentId === selectedChildId && item.kind === kind); setConsent.mutate({ studentId: selectedChildId as string, kind, granted: !current?.granted }); }
  if (childrenQuery.isLoading) return <LoadingFallback label={t("children.loading")} />;
  if (childrenQuery.isError) return <RouteState title={t("children.loadError")} actionLabel={t("children.retry")} onAction={childrenQuery.refetch} />;
  return <div className="portal-page"><div className="portal-page-heading"><div><span className="portal-eyebrow">{t("children.eyebrow")}</span><h1>{t("children.title")}</h1><p>{t("children.subtitle")}</p></div><div className="heading-actions"><Button variant="secondary" onClick={() => { setFormError(""); setLinkOpen(true); }}><Link2 size={17} /> {t("children.linkChild")}</Button><Button onClick={() => { setFormError(""); setChildOpen(true); }}><Plus size={17} /> {t("children.createChild")}</Button></div></div>
    <div className="children-card-grid">{(childrenQuery.data ?? []).map((item, index) => <motion.button type="button" className={`child-profile-card child-profile-card--button ${selectedChildId === item.id ? "is-selected" : ""}`} key={item.id} onClick={() => selectChild(item.id)} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }}><div className="child-card-status"><CheckCircle2 size={15} /> {selectedChildId === item.id ? t("children.selected") : t("children.verified")}</div><Avatar name={item.name} tone={item.avatarTone} size="lg" status="online" /><h2>{item.name}</h2><p>{item.username} · {item.grade}</p><div className="child-stats"><span><CheckCircle2 size={16} /><strong>{item.lessons}</strong><small>{t("children.lessonsUnit")}</small></span><span><Clock3 size={16} /><strong>{item.minutes}</strong><small>{t("children.minutesUnit")}</small></span></div><div className="child-last"><small>{t("children.lastActivity")}</small><strong>{item.lastActivity}</strong></div></motion.button>)}</div>
    {!childrenQuery.data?.length && <div className="portal-empty"><UsersRound size={30} /><h2>{t("children.emptyTitle")}</h2><p>{t("children.emptyDescription")}</p></div>}
    {selectedChild ? <section className="portal-card consent-panel"><div className="portal-section-head"><div><span>{t("children.consentEyebrow")}</span><h2>{t("children.consentTitle", { name: selectedChild.name })}</h2></div><div className="heading-actions"><Button size="sm" variant="secondary" onClick={() => setLoginsOpen(true)}><History size={15} /> {t("children.loginsHistory")}</Button><ShieldCheck size={22} /></div></div><div className="consent-list">{consentKinds.map((kind) => { const Icon = kind.icon; const granted = (consents.data ?? []).some((item) => item.studentId === selectedChildId && item.kind === kind.id && item.granted); return <button key={kind.id} disabled={consents.isLoading || setConsent.isPending} onClick={() => toggleConsent(kind.id)}><span className="consent-icon"><Icon size={18} /></span><span><strong>{kind.label}</strong><small>{kind.description}</small></span><i className={granted ? "is-active" : ""}>{granted ? t("children.consentOn") : t("children.consentOff")}</i></button>; })}</div>{consents.isError ? <div className="form-alert">{t("children.consentLoadError")}</div> : null}</section> : null}
    <Dialog open={linkOpen} onOpenChange={setLinkOpen}>{linkOpen && <DialogContent title={t("children.linkDialog.title")} description={t("children.linkDialog.description")}><form className="dialog-form" onSubmit={submitLink}><label className="field-group"><span>{t("children.linkDialog.codeLabel")}</span><div className="input-shell"><input autoFocus value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder={t("children.linkDialog.codePlaceholder")} required /></div></label>{formError && <div className="form-alert">{formError}</div>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={() => setLinkOpen(false)}>{t("children.linkDialog.cancel")}</Button><Button type="submit" loading={requestLink.isPending}>{t("children.linkDialog.submit")}</Button></div></form></DialogContent>}</Dialog>
    <Dialog open={childOpen} onOpenChange={setChildOpen}>{childOpen && <DialogContent title={t("children.childDialog.title")} description={t("children.childDialog.description")}><form className="dialog-form" onSubmit={submitChild}><div className="register-name-grid"><label className="field-group"><span>{t("children.childDialog.firstName")}</span><div className="input-shell"><input value={child.first_name} onChange={(event) => setChild((value) => ({ ...value, first_name: event.target.value }))} required /></div></label><label className="field-group"><span>{t("children.childDialog.lastName")}</span><div className="input-shell"><input value={child.last_name} onChange={(event) => setChild((value) => ({ ...value, last_name: event.target.value }))} required /></div></label></div><label className="field-group"><span>{t("children.childDialog.username")}</span><div className="input-shell"><input value={child.username} onChange={(event) => setChild((value) => ({ ...value, username: event.target.value }))} required /></div></label><label className="field-group"><span>{t("children.childDialog.tempPassword")}</span><div className="input-shell"><input type="password" value={child.password} onChange={(event) => setChild((value) => ({ ...value, password: event.target.value }))} minLength={8} required /></div></label>{formError && <div className="form-alert">{formError}</div>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={() => setChildOpen(false)}>{t("children.childDialog.cancel")}</Button><Button type="submit" loading={createChild.isPending}>{t("children.childDialog.submit")}</Button></div></form></DialogContent>}</Dialog>
    <LoginHistoryDialog open={loginsOpen} onOpenChange={setLoginsOpen} studentId={selectedChildId} title={t("children.loginHistoryTitle", { name: selectedChild?.name ?? t("children.loginHistoryStudentFallback") })} description={t("children.loginHistoryDescription")} />
  </div>;
}
